export const SOL_DECIMAL = 1_000_000_000;
export const SOLANA_RPC =
  "https://devnet.helius-rpc.com/?api-key=395ca45a-5a2f-4bdb-9ca8-224d7ccbf821";
export const COLLECTION_ID = "6REEjxT9CoDdDKPUxvFJQ8nFgbgScedxNn9zorZGtBi9";
export const COLLECTION_MINT = "CNWeeSxws4ULowBC3dLC7ekGnJi3KZLTBVhdWQ9aZs6z";
export const CANDYMACHINE_ID = "3RV9RuSnZvVavkjDwxbGmv9HYKyjqSuYg776pfTXGMKK";
export const ENDPOINT = "https://mugs-backend.vercel.app/";
export const COINGECKOAPIKEY = "CG-Y1F1ELjDqqq8pCKUiKpXhkmw";
export const MUGS_ENDPOINT = "https://api.mugmarket.xyz";
export const PINATA_APIKEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI2Yzg5ZjliNi0zNDM2LTQwN2ItOGQ2YS1jNjY3OWU2ZTBjZjUiLCJlbWFpbCI6Im5pbmVzYWlkLmFic0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiOTRiNTViODZmNGRlODcxYzU3OWQiLCJzY29wZWRLZXlTZWNyZXQiOiJhNDhkN2FiZTRkZTY1NTcyOTg5YTI2MWI1MTQzYzkyN2YwNTUxMWIyYzVjYjA2MWUxMzVhMmQ3MzQ5NzJhY2Q0IiwiZXhwIjoxNzUxMzYwMDY0fQ.gBciLJNTqmxu0InWjS5Yk-K_trFmu4_1eNAZJgsu7ZU";
export const PINATA_URL = "https://gateway.pinata.cloud/ipfs/";
